Repository tiangolo/meinheld-gunicorn-docker, pull requests merged in 2024-03, with the labels that each got.

#111 ✨ Add support for multi-arch builds, including support for arm64 (e.g. Mac M1)
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  scripts/build-push-all.sh
  scripts/build-push.sh
  scripts/build.sh
  scripts/docker-login.sh
  scripts/test-all.sh
  scripts/test.sh
Labels: feature

#112 📝 Update test badge in `README.md`
  README.md
Labels: docs

#113 📝 Update test badge in `README.md`
  README.md
Labels: docs

#114 🔧 Update `latest-changes.yml`
  .github/workflows/latest-changes.yml
Labels: internal

#120 🔧 Add GitHub templates for discussions and issues, and security policy
  .github/DISCUSSION_TEMPLATE/questions.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/privileged.yml
  SECURITY.md
Labels: internal
